db:
  repository: public.ecr.aws/g1o9h9r6/yunha-lab2
  tag: db-v1-amd64
  replicas: 1

redis:
  repository: public.ecr.aws/g1o9h9r6/yunha-lab2
  tag: redis-v1-amd64
  replicas: 1

app:
  repository: public.ecr.aws/g1o9h9r6/yunha-lab2
  tag: app-v1-amd64
  replicas: 1

nginx:
  repository: nginx
  tag: latest
  replicas: 1


ingress:
  healthCheckPath: /healthz
  host: app.choiyunha.com
  certificateArn: arn:aws:acm:us-east-2:862016452072:certificate/91cf5987-30e3-42d2-9f44-14d95ad48193
  group:
    name: shared-alb
    order: "10"
